# Generated by Django 6.0.6 on 2026-07-01 18:37

import appliance_module.model.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('appliance_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price_per_unit', models.IntegerField()),
            ],
            options={
                'db_table': 'appliances',
            },
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('endpoint_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_add', models.GenericIPAddressField(blank=True, null=True)),
                ('connection', models.BooleanField(default=False)),
                ('token', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'endpoints',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('balance', models.IntegerField()),
                ('key', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'rooms',
                'constraints': [models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='balance_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='RoomTOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', appliance_module.model.fields.EncryptedCharField()),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appliance_module.room')),
            ],
            options={
                'db_table': 'room_totps',
            },
        ),
        migrations.CreateModel(
            name='RunsLog',
            fields=[
                ('logid', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inic_units', models.IntegerField()),
                ('inic_price', models.IntegerField()),
                ('state', models.IntegerField(choices=[(1, 'Running'), (2, 'Finished'), (3, 'Aborted')], default=1)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('final_units', models.IntegerField(blank=True, null=True)),
                ('final_price', models.IntegerField(blank=True, null=True)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appliance_module.appliance')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appliance_module.endpoint')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appliance_module.room')),
            ],
            options={
                'db_table': 'runs_logs',
            },
        ),
        migrations.CreateModel(
            name='EndpointApplianceStateRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_occupied', models.BooleanField(default=False)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliance_module.appliance')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliance_module.endpoint')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appliance_module.room')),
                ('log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appliance_module.runslog')),
            ],
            options={
                'db_table': 'endpoint_appliance_states',
                'unique_together': {('endpoint', 'appliance')},
            },
        ),
    ]
