# Generated by Django 6.0.6 on 2026-07-01 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appliance_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidPayments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('amount', models.IntegerField()),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('payment_time', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValidPayments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('amount', models.IntegerField()),
                ('payment_time', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appliance_module.room')),
            ],
        ),
    ]
